### PR TITLE
Create 20151103.md

### PR DESCRIPTION
**Pull request by sjpiper145**

### CODE REVIEW

**Comment by lhovo** [comment]
How are the members list populated?
I have noticed that my name has been on all of them though not being present for the meeting.

**Comment by jhogendorn** [comment]
I would assume from the paper list passed around at the meeting? @sjpiper145 would have to clarify.

**Comment by sjpiper145** [comment]
My mistake, I've been using my own version of the template and removing names.  I'll double check this one.

**Comment by sjpiper145** [comment]
What's the best way to fix this? Make a new pull request? Thanks for picking this up, Luke.

**Comment by JAMESBOWLER** [comment]
yep make another pull request

**Comment by jhogendorn** [comment]
Just update the existing one?

On Thursday, 5 November 2015, JAMESBOWLER <notifications@github.com> wrote:

> yep make another pull request
>
> On Thu, Nov 5, 2015 at 8:52 PM, sjpiper145 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > What's the best way to fix this? Make a new pull request? Thanks for
> > picking this up, Luke.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/HSBNE/hsbne.github.com/pull/109#issuecomment-154029174>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/HSBNE/hsbne.github.com/pull/109#issuecomment-154046465>
> .
>


-- 
Apologies for any terseness, this was sent from my mobile.

Regards,

Joshua Hogendorn
PH: 0407710007

**Comment by sjpiper145** [comment]
Ah, figured it out.  Fixed!

**Pull request merged**
