### PR TITLE
Minutes for meeting 13-01-15

### PR DESCRIPTION
**Pull request by specialteasauce**
Please wait for Victor's approval to sign on executive email before publishing.

### CODE REVIEW

**Comment by lhovo** [comment]
Unfortunatly all purchases are voided due to no finatial report.

**Comment by jhogendorn** [comment]
pardon, luke?

Regards,

Joshua Hogendorn
PH: 0407710007

**Comment by nog3** [comment]
He's referring to the motion I made at a meeting in Dec that no votes on
financial items could happen without an update from the treasurer. (
http://hsbne.org/admin/meeting/20141118.html )

 In addition, a financial report must be presented by the treasurer before
any financial vote, and give an update on immediately spendable money- in
person or paper. Seconded by Aaron For 13 Against 0 Abstain 2

I'm guessing it's the chairperson's responsibility to ensure that is
upheld. Are you back next week for the meeting Luke so we can sort this out?

**Comment by nog3** [comment]
Hey @specialteasauce I remember @jhogendorn giving a financial report just before the financial items. Victor and Sven should be able to confirm this at least. Can you please confirm and submit a correction that adds it?

**Comment by JAMESBOWLER** [comment]
It is the treasures responsibility to have report before the meeting. If
there is enough in the budget I would suggest letting it slide. If not it
is up to president to take this matter to a meeting.

Everyone should not be expected to do everything every time. The last
financial report was good so Luke ultimately what do you want to happen.
Can we afford these items?

**Comment by lhovo** [comment]
I think this has been sorted internally, as there was a report given on the
night before the expenditure the notes will be admended to reflect this.

I am happy this will satisfy the requirement.

**Comment by specialteasauce** [comment]
Changes are there

**Pull request merged**
