### PR TITLE
New File

### PR DESCRIPTION
**Pull request by daveseff**

### CODE REVIEW

**Comment by jhogendorn** [comment]
I've updated the missing information as best I can.

This is still missing a members list, as such I'd like it to have a members list before acceptance/merge.

**Comment by jabelone** [comment]
Hello... Anyone here?

hello

**Comment by jabelone** [comment]
@nog3 @jhogendorn can we pls close or finalise whatever this was?

**Comment by jhogendorn** [comment]
I have no stake in this as I no longer maintain the website nor am I bothering to enforce good meeting notes. I don’t mind whatever people decide to do.

**Comment by nog3** [comment]
I'm merging this, it's unlikely we'll ever be able to get a members list now and it's probably better to have a record of a meeting than nothing.

**Pull request merged**
