### PR TITLE
Improving the Visit Page

### PR DESCRIPTION
**Pull request by jdownie**
I've made a few smaller changes to the car directions. Closer to what you had in mind?

### CODE REVIEW

**Comment by jhogendorn** [comment]
this looks better :) the taskade ticket is mainly about updating the public transport instructions because there are new services etc.

might be good to add to the description to look for the car in the container? pretty big landmark.

**Comment by jdownie** [comment]
Oooh, i think that by pushing another commit i've automatically updated my pull request. Is that all I have to do?

**Comment by jhogendorn** [comment]
> Oooh, i think that by pushing another commit i've automatically updated my pull request. Is that all I have to do?

yep :)

**Comment by jhogendorn** [comment]
thats looking pretty good mate!

**Comment by jdownie** [comment]
Those changes to the login page are out now. This PR should now be limited to only the "how to get here" instructions.

**Comment by jhogendorn** [comment]
Finally had some time to catch up and check this out. looks good, thanks for the work mate!

**Review by jhogendorn — APPROVED** [review]

**Pull request merged**
