### PR TITLE
New meeting

### PR DESCRIPTION
**Pull request by daveseff**

### CODE REVIEW

**Comment by jhogendorn** [comment]
can this be finished and merged?

**Comment by daveseff** [comment]
Yes. I've been slacko. Ill be submitting a PR soon

On July 15, 2016 4:37:42 PM GMT+10:00, Joshua Hogendorn <notifications@github.com> wrote:
>can this be finished and merged?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/HSBNE/hsbne.github.com/pull/124#issuecomment-232872671

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jhogendorn** [comment]
I don't understand, this is already a pr, its just incomplete.

Regards,

Joshua Hogendorn
PH: 0407710007

**Comment by daveseff** [comment]
Sorry. I thought this was for this last Tuesday. I don't know why this one isn't merged. I'll check it out.

**Pull request merged**
