### PR TITLE
Create 20160531.md

### PR DESCRIPTION
**Pull request by daveseff**

### CODE REVIEW

**Comment by nog3** [comment]
This just needs the signed: to be Steph Piper (the President always signs off the notes) and legal names in the Members List. Lysa is Leah Singh.

Also I know their handwriting can be hard so:
David Bussenschutt and Sven Hanzka.

If you need a hand adding these changes in a commit to this pull request feel free to nudge me :)

**Comment by jhogendorn** [comment]
In theory, at least, you should get steph to 'sign off' via an email or
something so you have a paper trail.

The point of 'signing' is so they can catch any errors you have made.

Regards,

Joshua Hogendorn
PH: 0407710007

**Comment by lhovo** [comment]
sonated by Nikki <- typo?

**Comment by daveseff** [comment]
Yes. That happens when I'm trying to type as fast as people are speaking. :)

**Comment by davidbuzz** [comment]
Also...it doesn't have to be steph/president that signs - off on the
minutes...any is legally equavilant.

**Comment by nog3** [comment]
Fixes look good, merged.

**Pull request merged**
