### PR TITLE
Bootstrap 3.3.6 + Blurb Change

### PR DESCRIPTION
**Pull request by nog3**
So this all works in local, but there might be some alignment things I haven't noticed.

@jhogendorn can you check this over to make sure it works for you as well before we merge.

### CODE REVIEW

**Comment by jhogendorn** [comment]
A quick readthrough shows that this is also design/copy changes, not just a bootstrap upgrade.

I'd prefer it if you could split those changes out so they can be discussed separately.

**Comment by nog3** [comment]
I tried to rebase the blurb change out but it was too much effort. I've renamed the PR to be more accurate.

Copy change has been approved by exec in the exec mailing list.

**Comment by jhogendorn** [comment]
Remind me to show you how to rebase sometime in the future.

I have no strong feelings on all this really, and you're the grand github poobah so do whatever you think is best.

**Comment by nog3** [comment]
Personally I wanted to make sure it worked for you before I pushed because
you're the most familiar with the codebase. Didn't want to break things :)

**Pull request merged**
