### PR TITLE
update rules

### PR DESCRIPTION
**Pull request by jabelone**

### CODE REVIEW

**Comment by jabelone** [comment]
These rules were approved and are now pending adoption by the OFT.

**Comment by jhogendorn** [comment]
This was merged without approval. @jabelone please resubmit this pr.

**Comment by jhogendorn** [comment]
A note for those following, WE ABSOLUTELY CANNOT PUBLISH NEW RULES ON THE OFFICIAL MEDIUM OF THE WEBSITE BEFORE THEY ARE ACCEPTED BY THE OFT.

**Comment by davidbuzz** [comment]
Perhaps we need a clearer way to manage this intermediate state of 'approved by membership+approved by exec, but not approved by OFT' ?

**Comment by jhogendorn** [comment]
that would be a lack of comment from an executive stating 'approved by oft by correspondence recieved on date x'

**Comment by jhogendorn** [comment]
I called the OFT today and these rules have been approved, please revive and apply :)

**Pull request merged**
